services:
  flutter-builder:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: legacy_flutter_env
    restart: unless-stopped
    ports:
      - "8080:80" # Expone Nginx por si decides darle uso web más adelante
    volumes:
      # Mapea la carpeta local del código fuente hacia /app dentro del contenedor
      - ./codigo_flutter:/app
    working_dir: /app
